# Generated by Django 4.1.7 on 2023-02-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.SmallIntegerField(choices=[(1, 'Backlog'), (2, 'In progress'), (3, 'Done')], default=1)),
                ('due_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
